version: "3"
services:
  redis:
    image: redis:latest
    container_name: airbnb_redis
    ports:
      - 6379:6379
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    container_name: airbnb_postgres_db
    environment:
      database: airbnb_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
      
