source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'
gem 'rails', '~> 7.0.0', '>= 7.0.0'

gem 'pg', '~> 1.1' # Use postgresql as the database for Active Record
gem 'redis', '~> 4.0' #key, value store
gem 'puma', '~> 5.0' # Use Puma as the app server
gem 'sass-rails', '>= 6' # Use SCSS for stylesheets
gem 'webpacker', '~> 5.0' # Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'jbuilder', '~> 2.7' # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "view_component" #resuable view components
gem "devise" #auth
gem "config" #config library to manage dev, prod, test, and secrets
gem 'bootsnap', '>= 1.4.4', require: false # Reduces boot times through caching; required in config/boot.rb
gem "sprockets-rails"
# gem 'image_processing', '~> 1.2' # Use Active Storage variant
gem "turbo-rails", "~> 1.0"

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw] # Call 'byebug' anywhere in the code to stop execution and get a debugger console
end

group :development do
  gem 'web-console', '>= 4.1.0' # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen', '~> 3.3'
  gem 'spring' # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
end

group :test do
  gem 'capybara', '>= 3.26' # Adds support for Capybara system testing and selenium driver
  gem 'selenium-webdriver'
  gem 'webdrivers'   # Easy installation and use of web drivers to run system tests with browsers
  gem 'rspec-rails'
end