// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import NavProfileController from "./nav_profile_controller.js"
application.register("nav-profile", NavProfileController)

import LoginSignupController from "./login_signup_controller.js"
application.register("login-signup", LoginSignupController)