name: Build Process
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: "./airbnb"
          push: true
          tags: "mikepresman/airbnbclone:nightly-${{steps.date.outputs.date}}"
