name: "Developer Workflow"
on: pull_request

jobs:
  linter:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.GITHUB_REF_NAME }}

    - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0

    - name: rubocop
      uses: reviewdog/action-rubocop@v2
      with:
        rubocop_version: gemfile