name: "Workflow"
on: pull_request

jobs:
  build:
    runs-on: "ubuntu-latest"
      steps:
      - uses: actions/checkout@v1

      - name: Rubocop Linter
        uses: luizfonseca/github-actions-rubocop@1.5.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}