name: "Developer Workflow"
on: pull_request

jobs:
  runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        ref ${{ env.GITHUB_REF_NAME }}

    - name: Rubocop Linter
      uses: luizfonseca/github-actions-rubocop@1.5.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}